#!/bin/bash

echo "Generating Panel token..."
python bot/scripts/generate_onetime_pass.py > bot/scripts/token.txt

echo "Building containers"
docker-compose build --no-cache
echo "Starting container up"
docker-compose up -d

python bot/scripts/print_onetime_pass.py